CREATE TABLE notebook (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address TEXT NOT NULL,
    state TEXT NOT NULL,
    zipcode TEXT NOT NULL,
    status TEXT NOT NULL,
    price INTEGER DEFAULT 0 NOT NULL,
    comments TEXT
)



    